import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ThreeScene from "../components/ThreeScene";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ORT Web Example</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Use ORT Web
        </h1>
          <ThreeScene width={800} height={600}/>
      <div id="result" className="mt-3">
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://onnxruntime.ai/docs"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}

export default Home
